#! /usr/bin/env perl

use strict;
use warnings;

#
# A Munin plugin.
#
# Fetches network interface traffic for Munin via SNMP.
#

my $host = exists $ENV{'host'} ? $ENV{'host'} : 'localhost';

my $oid_subtree = '.1.3.6.1.2.1'; # interfaces MIB

if (exists $ARGV[0] and $ARGV[0] eq 'autoconf') {
    print "yes\n";
    exit 0;
}

open(my $mib, "-|", "snmpwalk -v2c -c public $host $oid_subtree")
    or die "cannot open: $!";

my (@interfaces, @bytes_in, @bytes_out);

while (<$mib>) {
    if (/^IF-MIB::ifName\./)           { pushv (\@interfaces) }
    if (/^IF-MIB::ifHCInOctets\./)     { pushv (\@bytes_in) }
    if (/^IF-MIB::ifHCOutOctets\./)    { pushv (\@bytes_out) }
}

my $offset = 0;

if (exists $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title interface traffic\n";
    print "graph_args --base 1000\n";
    print "graph_vlabel bits in (-) / out (+)\n";
    print "graph_category network\n";
    print "graph_info This graph shows network interface traffic.\n";

    foreach my $interface (@interfaces) {
        print "bytes_in_$interface.label $interface\n";
        print "bytes_in_$interface.type DERIVE\n";
        print "bytes_in_$interface.graph no\n";
        print "bytes_in_$interface.cdef bytes_in_$interface,8,*\n";
        print "bytes_in_$interface.min 0\n";
        print "bytes_out_$interface.label $interface\n";
        print "bytes_out_$interface.type DERIVE\n";
        print "bytes_out_$interface.negative bytes_in_$interface\n";
        print "bytes_out_$interface.cdef bytes_out_$interface,8,*\n";
        print "bytes_out_$interface.min 0\n";
        $offset++;
    }

    exit 0;
}

foreach my $interface (@interfaces) {
    print "bytes_in_$interface.value $bytes_in[$offset]" . "\n";
    print "bytes_out_$interface.value $bytes_out[$offset]" . "\n";
    $offset++;
}

sub getv {
    chomp; s/.*\s//;
}

sub pushv {
    my ($arg1) = @_;
    getv; push @$arg1, $_;
}
