#! /usr/bin/env perl

use strict;
use warnings;

#
# A Munin plugin.
#
# Fetches memory utilisation via SNMP.
#

my $host = exists $ENV{'host'} ? $ENV{'host'} : 'localhost';

my $oid_subtree = '.1.3.6.1.4.1.2021.4';  # UC Davis MIB

open(my $mib, "-|", "snmpwalk -v2c -c public $host $oid_subtree")
    or die "cannot open: $!";

if (exists $ARGV[0] and $ARGV[0] eq 'autoconf') {
    print "yes\n";
    exit 0;
}

my (@mem_total, @mem_avail);

while (<$mib>) {
    if (/^UCD-SNMP-MIB::memTotalReal\./) { pushv (\@mem_total) }
    if (/^UCD-SNMP-MIB::memAvailReal\./) { pushv (\@mem_avail) }
}

my $offset = 0;

if (exists $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_args --base 1024 -l 0 --vertical-label Bytes \n";
    print "graph_title Memory usage\n";
    print "graph_category system\n";

    foreach my $mem_total (@mem_total) {
        print "mem_used_$offset.label used($offset)\n";
        print "mem_used_$offset.draw AREA\n";
        print "mem_avail_$offset.label avail($offset)\n";
        print "mem_avail_$offset.draw STACK\n";
        $offset++;
    }

    exit 0;
}

foreach my $mem_total (@mem_total) {
    print "mem_used_$offset.value "
        . ($mem_total-$mem_avail[$offset]) * 1024 . "\n";
    print "mem_avail_$offset.value " . ($mem_avail[$offset] * 1024) . "\n";
    $offset++;
}

sub getv {
    chomp; s/.*\s+(\d+)\s+\S+/$1/;
}

sub pushv {
    my ($arg1) = @_;
    getv; push @$arg1, $_;
}
