#! /usr/bin/env perl

use strict;
use warnings;

#
# A Munin plugin.
#
# Fetches percentage of multiprocessor CPU utilisation via SNMP.
#

my $host = exists $ENV{'host'} ? $ENV{'host'} : 'localhost';

my $oid_subtree = '.1.3.6.1.2.1.25.3'; # host resources MIB

if (exists $ARGV[0] and $ARGV[0] eq 'autoconf') {
    print "yes\n";
    exit 0;
}

open(my $mib, "-|", "snmpwalk -v2c -c public -- $host $oid_subtree")
or die "cannot open: $!";

my @cpu_load;

while (<$mib>) {
    if (/^HOST-RESOURCES-MIB::hrProcessorLoad\./) { pushv (\@cpu_load) }
}

my $offset = 0;

if (exists $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title CPU usage\n";
    print "graph_args --upper-limit 100 -l 0\n";
    print "graph_vlabel %\n";
    print "graph_scale no\n";
    print "graph_info This graph shows CPU utilisation.\n";
    print "graph_category system\n";

    foreach my $cpu_load (@cpu_load) {
        print "cpu_$offset.label cpu$offset\n";
        $offset++;
    }

    exit 0;
}

foreach my $cpu_load (@cpu_load) {
    print "cpu_$offset.value $cpu_load\n";
    $offset++;
}

sub getv {
    chomp; s/.*\s//;
}

sub pushv {
    my ($arg1) = @_;
    getv; push @$arg1, $_;
}
